### ISSUE TITLE
frames and processed directory locations

### ISSUE THREAD

**Issue by Oppfields** [STribbey125/rembg_from_video#1]
When running the script from inside its downloaded directory the frames and processed directories are created outside the enclosing directory and the individual frames are saved inside the directory. When the frames have been extracted a path error occurs as the frames are not found in the correct location.  

rembg_from_video/frames
... image_01
... image_02
... rembg_video.py
rembg_from_video/processed
rembg_from_video

Rembg works correctly.

**Comment by seth-tribbey** [comment]
I'm not sure how to recreate your issue. I just cloned the repo and successfully ran a video with this as the result:
![Capture](https://user-images.githubusercontent.com/16655817/164319417-889239fa-0935-406b-a8c8-c2e21835e595.JPG)
I just pushed a small change to the file IO, so perhaps that will help you.

**Comment by Oppfields** [comment]
The first test was on Linux, I've now cloned it on macOS and get the same issue with the directories being created outside of the script directory:

<img width="444" alt="Screenshot 2022-04-21 at 00 09 44" src="https://user-images.githubusercontent.com/1633771/164339491-87193f17-80cb-448f-a941-d1bb88f5b870.png">

`Unrecognized option 'crf'.
Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "/Users/sumo/gitrepo/rembg_video/rembg_video.py", line 53, in <module>
    ffmpeg.run(stream)
  File "/Users/sumo/miniconda3/envs/remgs/lib/python3.9/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)`

**Comment by seth-tribbey** [comment]
I would hazard that you're having an issue with ffmpeg. 
Check here: https://superuser.com/questions/1302753/ffmpeg-unrecognized-option-crf-error-splitting-the-argument-list-option-not

**Comment by Oppfields** [comment]
Thanks, that makes sense. I've just checked my MacOS Homebrew FFmpeg install and it lacks --enable-gpl --enable-libx264. Will see if brew has the option to add the libraries if not I can switch to a Linux machine for testing.
